### ISSUE TITLE
如何注册阿里云盘开发者

### ISSUE THREAD

**Issue by xiaodatao2007** [520yxl/Aliyundrive_Refresh_Token_php#1]
您好，如何注册阿里云盘开发者， 在什么地方，感谢！

**Comment by 520yxl** [comment]
> 您好，如何注册阿里云盘开发者， 在什么地方，感谢！
![image](https://7up.pics/images/2023/08/18/20230818141730549.jpg)

**Comment by xiaodatao2007** [comment]
好的，感谢回复！
