### ISSUE TITLE
请问这个参数咱们这里可以设置吗？

### ISSUE THREAD

**Issue by ypq123456789** [520yxl/Aliyundrive_Refresh_Token_php#3]
<img width="548" alt="{44DFF3F4-45D9-4228-9372-086D5F9E7D6E}" src="https://github.com/520yxl/Aliyundrive_Refresh_Token_php/assets/114487221/13d49269-82ed-499c-841e-86de083a6210">

**Comment by 520yxl** [comment]
可以自行添加参数进行请求

**Comment by 520yxl** [comment]
不过，我这个PHP文件只是进行获取刷新令牌而已，你这个跟这个无关的

**Comment by ypq123456789** [comment]
大佬，这个看视频的直链有效期，是不是只有alist和小雅能设置，我们自己有开发者账号的也没法设置



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月9日(周五) 上午10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [520yxl/Aliyundrive_Refresh_Token_php] 请问这个参数咱们这里可以设置吗？ (Issue #3)




 
不过，我这个PHP文件只是进行获取刷新令牌而已，你这个跟这个无关的
