### ISSUE TITLE
请问window系统扫码授权工具 能否提供一个权限为 file:all:write 的版本？多谢！

### ISSUE THREAD

**Issue by zhychen1173** [520yxl/Aliyundrive_Refresh_Token_php#4]
现在的版本扫码授权后，只授权了读取权限，没有文件写入权限。
如果可以的话，万分感谢！

**Comment by 520yxl** [comment]
已加上，感谢反馈

**Comment by zhychen1173** [comment]
感谢更新。
这个版本下载解压后，windows defender 报 Program:Win32/Wacapew.C!ml 威胁。此前那个版本并没有报这个问题，不知道怎么回事。

**Comment by 520yxl** [comment]
先退出安全软件使用吧，我有空排查一下
