### ISSUE TITLE
访问出现500错误，网页无法正常运作

### ISSUE THREAD

**Issue by iceyheart** [520yxl/Aliyundrive_Refresh_Token_php#6]
![1718861678585](https://github.com/520yxl/Aliyundrive_Refresh_Token_php/assets/40313247/51306fc1-aa23-46aa-87e8-96645d045ca2)

**Comment by 520yxl** [comment]
> 
> ![1718861678585](https://github.com/520yxl/Aliyundrive_Refresh_Token_php/assets/40313247/51306fc1-aa23-46aa-87e8-96645d045ca2)
> 
> 

请检查一下自己的网络环境，这个ip地址属于局域网ip

**Comment by iceyheart** [comment]
server {
        listen 8888;
        server_name localhost;
        root /etc/xiaoya;
        location ~ \.php$ {
    fastcgi_pass   127.0.0.1:10000;
    fastcgi_index  aliyuntoken.php;
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
   # fastcgi_param  PATH_INFO       $fastcgi_script_name;
    include        fastcgi_params;
   # try_files $uri =404;
}
}

**Comment by iceyheart** [comment]
另外，在vps上通过域名也部署了，结果一样。php版本8.2

**Comment by 520yxl** [comment]
> 另外，在vps上通过域名也部署了，结果一样。php版本8.2

安装个远程软件，告诉我什么远程软件，还有远程ID是多少

**Comment by iceyheart** [comment]
https://aliyuntoken.ymschh.top/index.php #测试php工作情况
https://aliyuntoken.ymschh.top/aliyundrive.php #无法打开

**Comment by 520yxl** [comment]
> https://aliyuntoken.ymschh.top/index.php #测试php工作情况 https://aliyuntoken.ymschh.top/aliyundrive.php #无法打开

试一下，关闭Cloudflare

**Comment by iceyheart** [comment]
试过了，一样的

**Comment by 520yxl** [comment]
> 另外，在vps上通过域名也部署了，结果一样。php版本8.2

版本换到php7的，不兼容php8

**Comment by iceyheart** [comment]
> > 另外，在vps上通过域名也部署了，结果一样。php版本8.2
> 
> 版本换到php7的，不兼容php8

换了7.4，还是一样

**Comment by 520yxl** [comment]
> > > 另外，在vps上通过域名也部署了，结果一样。php版本8.2
> > 
> > 版本换到php7的，不兼容php8
> 
> 换了7.4，还是一样
方便远程排查吗？

**Comment by iceyheart** [comment]
> > > > 另外，在vps上通过域名也部署了，结果一样。php版本8.2
> > > 
> > > 
> > > 版本换到php7的，不兼容php8
> > 
> > 
> > 换了7.4，还是一样
> > 方便远程排查吗？

使用RayLink即可对我发起远程连接
设备代码：720 252 367
访问密码：Z3ASa2BT
RayLink下载地址：https://www.raylink.live/download.html
