### ISSUE TITLE
您好，请问一下，扫码登录不返回信息如何处理？

### ISSUE THREAD

**Issue by itswl** [520yxl/Aliyundrive_Refresh_Token_php#7]
<img width="585" alt="image" src="https://github.com/520yxl/Aliyundrive_Refresh_Token_php/assets/32117460/18600ba9-6cf5-4fa5-ac5f-495e78c66bc3">

**Comment by 520yxl** [comment]
更换浏览器试一试，还是不行，反馈给官方
