### ISSUE TITLE
点击跳转阿里云盘授权登录，跳转界面出错

### ISSUE THREAD

**Issue by michealhansun** [520yxl/Aliyundrive_Refresh_Token_php#8]
{
    "code": "InvalidRedirectUri",
    "message": "invalid redirect_uri",
    "requestId": "f974258e-9b0c-4928-963a-47f9799e7aae"
}

**Comment by 520yxl** [comment]
去官方文档查一下是什么原因，我这就不回复了，直接关闭议题
