### ISSUE TITLE
PHP提示警报

### ISSUE THREAD

**Issue by Simonzhang8** [520yxl/Aliyundrive_Refresh_Token_php#9]
Warning: Undefined array key "code" in /www/wwwroot/alipan-api/index.php on line 21

Warning: Undefined array key "refresh_token" in /www/wwwroot/alipan-api/index.php on line 68

参考网址：https://alipan.api.zxm86.cn

**Comment by 520yxl** [comment]
> 
> Warning: Undefined array key "code" in /www/wwwroot/alipan-api/index.php on line 21
> 
> Warning: Undefined array key "refresh_token" in /www/wwwroot/alipan-api/index.php on line 68
> 
> 参考网址：https://alipan.api.zxm86.cn

PHP版本切换到7.4

**Comment by Simonzhang8** [comment]
> > Warning: Undefined array key "code" in /www/wwwroot/alipan-api/index.php on line 21
> > Warning: Undefined array key "refresh_token" in /www/wwwroot/alipan-api/index.php on line 68
> > 参考网址：https://alipan.api.zxm86.cn
> 
> PHP版本切换到7.4

好的好的，可以了，非常感谢
